import type { MonsterFocusBonusType } from "../shared/types";

export const monsterFocusConfig = {
  unlockedSlotsDefault: 1,
  maxSlots: 3,
  defaultRemainingHunts: 10,
  activationGoldCost: 0,
  rerollGoldCostBase: 250,
  bonusPercentByType: {
    experience: 10,
    loot: 8,
    gold: 8,
    supplies: 6,
    risk: 5,
  } satisfies Record<MonsterFocusBonusType, number>,
};

export const monsterFocusBonusLabels: Record<MonsterFocusBonusType, string> = {
  experience: "Hunter's Insight",
  loot: "Scavenger Mark",
  gold: "Bounty Mark",
  supplies: "Conservation Mark",
  risk: "Defensive Study",
};

export const monsterFocusBonusDescriptions: Record<MonsterFocusBonusType, string> = {
  experience: "Increases XP against the focused creature.",
  loot: "Increases final loot value when the focused creature is hunted.",
  gold: "Increases gold generated by the focused creature.",
  supplies: "Reduces supplies while hunting the focused creature.",
  risk: "Reduces hunt risk when the focused creature is present.",
};

export const monsterFocusBonusTypes = Object.keys(
  monsterFocusConfig.bonusPercentByType,
) as MonsterFocusBonusType[];
